const words = [
  { word: "Harmonia", clue: "Equilíbrio e concordância entre elementos diferentes." },
  { word: "Sonho", clue: "Uma série de imagens, ideias, emoções e sensações que ocorrem involuntariamente na mente durante o sono." },
  { word: "Aventura", clue: "Uma experiência emocionante ou arriscada." },
  { word: "Memória", clue: "A capacidade de reter e recordar informações e experiências passadas." },
  { word: "Sorriso", clue: "Expressão facial que indica felicidade, alegria ou satisfação." },
  { word: "Reflexo", clue: "Resposta automática e involuntária a um estímulo." },
  { word: "Curiosidade", clue: "Vontade de aprender, descobrir ou conhecer algo novo." },
  { word: "Paz", clue: "Estado de tranquilidade e ausência de conflito." },
  { word: "Caminho", clue: "Rota ou trajeto que leva de um lugar a outro." },
  { word: "Brilho", clue: "Luz intensa que emana de algo." },
  { word: "Segredo", clue: "Informação confidencial conhecida apenas por poucas pessoas." },
  { word: "Viagem", clue: "Deslocamento de um lugar para outro, muitas vezes para fins recreativos ou educacionais." },
  { word: "Amizade", clue: "Relação afetuosa entre duas ou mais pessoas." },
  { word: "Natureza", clue: "O mundo físico e todas as coisas que existem naturalmente, incluindo plantas, animais, rochas e fenômenos naturais." },
  { word: "Simplicidade", clue: "Qualidade de ser fácil de entender ou realizar." },
  { word: "Saudade", clue: "Sentimento nostálgico de falta ou desejo por algo ou alguém que está ausente." },
  { word: "Liberdade", clue: "Estado de estar livre de restrições ou controle." },
  { word: "Desejo", clue: "Sentimento de querer algo intensamente." },
  { word: "Crescer", clue: "Aumentar em tamanho, número, importância ou maturidade." },
  { word: "Fantasia", clue: "Imaginação criativa ou uma história imaginária." },
  { word: "Alegria", clue: "Sentimento de grande felicidade ou prazer." },
  { word: "Cantar", clue: "Produzir música ou sons vocais com a voz." },
  { word: "Verdade", clue: "Conformidade com os fatos ou a realidade." },
  { word: "Aprender", clue: "Adquirir conhecimento ou habilidade através do estudo ou da experiência." },
  { word: "Descoberta", clue: "Ato ou processo de encontrar algo novo ou anteriormente desconhecido." },
  { word: "Coragem", clue: "Força interior para enfrentar situações desafiadoras ou perigosas." },
  { word: "Amor", clue: "Sentimento profundo de afeição, carinho e cuidado por outra pessoa." },
  { word: "Felicidade", clue: "Estado de estar feliz ou contente." },
  { word: "Casa", clue: "Residência ou lugar onde alguém vive." },
  { word: "Tempo", clue: "Dimensão na qual os eventos ocorrem em uma sequência irreversível." },
  { word: "Sorvete", clue: "Uma sobremesa gelada feita de leite, açúcar e saborizantes." },
  { word: "Cachorro", clue: "Um animal de estimação conhecido por sua lealdade e companheirismo." },
  { word: "Jardim", clue: "Um espaço ao ar livre onde plantas, flores e vegetação são cultivados." },
  { word: "Chocolate", clue: "Um doce feito a partir do cacau, muitas vezes consumido em forma de barra ou bebida quente." },
  { word: "Piano", clue: "Um instrumento musical de teclas pretas e brancas." },
  { word: "Família", clue: "Um grupo de pessoas relacionadas por laços de sangue, casamento ou adoção." },
  { word: "Fotografia", clue: "A arte de capturar imagens usando uma câmera." },
  { word: "Lobo", clue: "Um mamífero carnívoro que vive em matilhas e é conhecido por sua astúcia." },
  { word: "Girafa", clue: "Um mamífero herbívoro de pescoço longo, que vive nas savanas africanas." },
  { word: "Panda", clue: "Um mamífero da família dos ursídeos, conhecido por sua pelagem preta e branca." },
  { word: "Tigre", clue: "Um grande felino carnívoro, conhecido por suas listras e força." },
  { word: "Leão", clue: "Um grande felino conhecido por sua juba e por ser o 'rei' da savana." },
  { word: "Gorila", clue: "Um grande primata que vive nas florestas tropicais da África." },
  { word: "Baleia", clue: "Um mamífero marinho de grande porte, conhecido por sua imponência e canto." },
  { word: "Rinoceronte", clue: "Um mamífero herbívoro de pele espessa e chifres, encontrado em diversas regiões do mundo." },
  { word: "Pinguim", clue: "Uma ave marinha não voadora, conhecida por sua plumagem preta e branca e sua habilidade de nadar." }
];
  
export default function getWord() {
    const index = Math.floor(Math.random() * words.length);
    return words[index];
  }